[package]
name = "murmurat-core"
version = "0.1.0"
edition = "2024"

[dependencies]
aes = "0.8.4"
bytes = "1.10.1"
ctr = "0.9.2"
num-bigint = "0.4.6"
num-traits = "0.2.19"
rand = "0.8"
rsa = "0.9.8"
sha3 = "0.10"
