[package]
name = "murmurat-exploit"
version = "0.1.0"
edition = "2024"

[dependencies]
pcap-parser = { version = "0.16.0", features = ["data"] }
murmurat-core = { path = "../murmurat-core" }
bytes = "1.10.1"
chrono = "0.4"
